- run: mv Runner.app/ Payload
    working-directory: build/ios/iphoneos

  - name: Re-sign with ldid
    run: |
      # Make sure ldid is installed (the macOS system is not installed by default).
      brew install ldid || true

      # Re-sign the executable file
      ldid -S -M build/ios/iphoneos/Payload/Runner.app/Runner

  - name: Zip output
    run: zip -qq -r -9 FlutterIpaExport.ipa Payload
    working-directory: build/ios/iphoneos
